-- 
--  Sea el conjunto de tablas de la base de datos...
-- 
--  Escriba una consulta que retorne el total 
--  de registros de la tabla tbl1 para el ano
--  2018
--
--  Rta/
--     strftime('%Y', c14)  CANT
--  0                 2018     6
--
--  >>> Escriba su codigo a partir de este punto <<<
-- 
SELECT COUNT(*) FROM tbl1 WHERE strftime('%Y', c14) = '2018';
